name: aws

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * 1,4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: aws
      - name: Create temp dir
        run: |-
          mkdir -p temp
      - name: Download the source list
        run: |-
          curl https://ip-ranges.amazonaws.com/ip-ranges.json -o ./temp/ip-ranges.json
      - name: Process the list
        run: |-
          # https://stackoverflow.com/questions/618378/select-unique-or-distinct-values-from-a-list-in-unix-shell-script
          # "sort is necessary in this command line, uniq only strips duplicate lines that are immediately after each other"

          # https://stackoverflow.com/a/40027637 - Pass variables in via jq arguments for easier readability and security.

          # Get list of regions from file; for each region, make regional file named $region.txt
          for row in $(jq -r '.prefixes[] | .region' ./temp/ip-ranges.json | sort | uniq); do
              jq -r --arg REGION "${row}" '.prefixes[] | select(.region == $REGION) | .ip_prefix' ./temp/ip-ranges.json > ${row}.txt
          done

          # Get list of services from file; for each service, make service file named $service.txt
          for row in $(jq -r '.prefixes[] | .service' ./temp/ip-ranges.json | sort | uniq); do
              jq -r --arg SERVICE "${row}" '.prefixes[] | select(.service == $SERVICE) | .ip_prefix' ./temp/ip-ranges.json > ${row}.txt
          done

      - name: Commit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
      - name: Push
        run: |-
          git push
