name: dshieldrbl

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * 1,4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: dshieldrbl
      - name: Create temp dir
        run: |-
          mkdir -p temp
      - name: Download the source list
        run: |-
          curl https://www.dshield.org/block.txt -o ./temp/cloudprefixes.txt
      - name: Process the list
        run: |-
          # Strip "Start" line, whitespace, and empty lines
          sed 's/Start.*//; s/^ *//; s/ *$//; /^$/d' ./temp/cloudprefixes.txt > ./temp/cloudprefixes2.txt
          # 's/Start.*//' => remove semicolon and everything after (including 0 chars)
          # 's/^ *//'  => left trim
          # 's/ *$//'  => right trim
          # '/^$/d'    => remove empty line

          # Parse table to CIDR range list
          awk -F '\t' 'OFS="/" {print $1, $3}' ./temp/cloudprefixes2.txt > dshieldrbl.txt
          # -F = input field separator
          # OFS = output field separator
          # 
          # File sample (tab separated)
          # Start	End	Netmask	Attacks	Name	Country	email
          # 192.168.28.0	192.168.28.255	24	1234	TELCOZZ	ZZ	abuse@example.com
          # 10.50.40.0  10.50.40.255	24	1234	NETWORK	AA	abuse@example.net
          # 169.254.33.0	169.254.33.255	24	1234	ARIN	BB	

      - name: Commit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
      - name: Push
        run: |-
          git push
