name: gcp

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * 1,4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: gcp
      - name: Create temp dir
        run: |-
          mkdir -p temp
      - name: Download the source list
        run: |-
          curl https://www.gstatic.com/ipranges/cloud.json -o ./temp/cloud.json
      - name: Process the list
        run: |-
          jq -r '.prefixes[] | select(.scope == "us-east1") | .ipv4Prefix' ./temp/cloud.json > us-east1.txt
      - name: Commit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
      - name: Push
        run: |-
          git push
