name: spamhausdrop

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * 1,4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: spamhausdrop
      - name: Create temp dir
        run: |-
          mkdir -p temp
      - name: Download the source list
        run: |-
          curl https://www.spamhaus.org/drop/drop.txt -o ./temp/cloudprefixes.txt
      - name: Process the list
        run: |-
          # Strip comments, whitespace, and empty lines
          sed 's/\;.*//; s/^ *//; s/ *$//; /^$/d' /temp/cloudprefixes.txt > spamhausdrop.txt
          # 's/\;.*//' => remove semicolon and everything after (including 0 chars)
          # 's/^ *//'  => left trim
          # 's/ *$//'  => right trim
          # '/^$/d'    => remove empty line

      - name: Commit
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
      - name: Push
        run: |-
          git push
